// 상품 데이터 모델. 화면 표시와 장바구니 로직에서 공통 사용한다.
class Product {
  final String id; // 상품 고유 ID
  final String title; // 상품명
  final String subTitle; // 상품 설명
  final int price; // 정가
  final String? image; // 이미지 경로 (없으면 null)
  final String category; // 카테고리
  int stock; // 재고 수량 (0이면 품절)
  final bool isNew; // 신상 여부
  final bool isSale; // 세일 여부
  final int? salePrice; // 세일가 (없으면 null)
  final List<String> options; // 옵션 리스트

  Product({
    required this.id,
    required this.title,
    required this.subTitle,
    required this.price,
    this.image,
    required this.category,
    this.stock = 10,
    this.isNew = false,
    this.isSale = false,
    this.salePrice,
    this.options = const [],
  });
}

// 테스트용 샘플 데이터
List<Product> dummyProducts = [
  Product(
    id: 'p1',
    title: '화이트 머그',
    subTitle: '핸드메이드 질감',
    price: 32000,
    image: 'assets/images/mug.jpg',
    category: '컵',
    stock: 12,
    isNew: true,
    options: const ['350ml', '420ml'],
  ),
  Product(
    id: 'p2',
    title: '모던 플레이트',
    subTitle: '미니멀 접시',
    price: 68000,
    image: 'assets/images/plate.jpg',
    category: '접시',
    stock: 6,
    options: const ['21cm', '26cm'],
  ),
  Product(
    id: 'p3',
    title: '스톤웨어 컵',
    subTitle: '자연스러운 컬러',
    price: 45000,
    image: 'assets/images/cup.jpg',
    category: '컵',
    stock: 9,
    isNew: true,
    options: const ['S', 'M', 'L'],
  ),
  Product(
    id: 'p4',
    title: '브러시 화병',
    subTitle: '공예 감성 포인트',
    price: 76000,
    image: 'assets/images/plate.jpg',
    category: '화병',
    stock: 5,
    isSale: true,
    salePrice: 69000,
    options: const ['Small', 'Large'],
  ),
  Product(
    id: 'p5',
    title: '라운드 볼',
    subTitle: '간식용 미니 볼',
    price: 41000,
    image: 'assets/images/plate.jpg',
    category: '볼',
    stock: 11,
    options: const ['소', '중'],
  ),
  Product(
    id: 'p6',
    title: '내추럴 트레이',
    subTitle: '테이블 베이스',
    price: 52000,
    image: 'assets/images/plate.jpg',
    category: '트레이',
    stock: 3,
    isSale: true,
    salePrice: 46000,
    options: const ['24cm'],
  ),
  Product(
    id: 'p7',
    title: '그린 머그',
    subTitle: '딥그린 컬러',
    price: 59000,
    image: 'assets/images/mug.jpg',
    category: '컵',
    stock: 7,
    options: const ['450ml'],
  ),
  Product(
    id: 'p8',
    title: '오프화이트 플레이트',
    subTitle: '데일리 플레이팅',
    price: 64000,
    image: 'assets/images/plate.jpg',
    category: '접시',
    stock: 8,
    options: const ['26cm'],
  ),
  Product(
    id: 'p9',
    title: '라인 머그',
    subTitle: '얇은 림 포인트',
    price: 39000,
    image: 'assets/images/mug.jpg',
    category: '컵',
    stock: 10,
    isNew: true,
    options: const ['화이트', '오프화이트'],
  ),
  Product(
    id: 'p10',
    title: '테이블 세트',
    subTitle: '2인 구성',
    price: 98000,
    image: 'assets/images/cup.jpg',
    category: '세트',
    stock: 4,
    isSale: true,
    salePrice: 88000,
    options: const ['2인', '4인'],
  ),
  Product(
    id: 'p11',
    title: '쉐이프 볼',
    subTitle: '깊이 있는 라인',
    price: 54000,
    image: 'assets/images/plate.jpg',
    category: '볼',
    stock: 6,
    options: const ['중', '대'],
  ),
  Product(
    id: 'p12',
    title: '아침 머그',
    subTitle: '가벼운 사용감',
    price: 28000,
    image: 'assets/images/cup.jpg',
    category: '컵',
    stock: 16,
    options: const ['S', 'M'],
  ),
  Product(
    id: 'p13',
    title: '아틀리에 볼',
    subTitle: '크리에이터 한정',
    price: 87000,
    image: 'assets/images/plate.jpg',
    category: '볼',
    stock: 5,
    options: const ['오프화이트', '라이트그레이'],
  ),
  Product(
    id: 'p14',
    title: '시그니처 머그',
    subTitle: '유약 흐름 포인트',
    price: 36000,
    image: 'assets/images/mug.jpg',
    category: '컵',
    stock: 10,
    options: const ['오프화이트', '그레이'],
  ),
  Product(
    id: 'p15',
    title: '프리미엄 화병',
    subTitle: '모던 실루엣',
    price: 120000,
    image: 'assets/images/plate.jpg',
    category: '화병',
    stock: 2,
    options: const ['대형'],
  ),
  Product(
    id: 'p16',
    title: '리미티드 머그',
    subTitle: '시즌 한정',
    price: 59000,
    image: 'assets/images/mug.jpg',
    category: '컵',
    stock: 0,
    isSale: true,
    salePrice: 49000,
    options: const ['450ml'],
  ),
  Product(
    id: 'p17',
    title: '매트 플레이트',
    subTitle: '데일리 플레이팅',
    price: 72000,
    image: 'assets/images/plate.jpg',
    category: '접시',
    stock: 5,
    isNew: true,
    options: const ['24cm', '28cm'],
  ),
  Product(
    id: 'p18',
    title: '미니 트레이',
    subTitle: '작은 소품 정리',
    price: 33000,
    image: 'assets/images/plate.jpg',
    category: '트레이',
    stock: 1,
    options: const ['오프화이트'],
  ),
  Product(
    id: 'p19',
    title: '오가닉 플레이트',
    subTitle: '자연스러운 라운드',
    price: 64000,
    image: 'assets/images/plate.jpg',
    category: '접시',
    stock: 8,
    options: const ['26cm'],
  ),
  Product(
    id: 'p20',
    title: '클레이 컵',
    subTitle: '손맛이 살아있는 텍스처',
    price: 45000,
    image: 'assets/images/cup.jpg',
    category: '컵',
    stock: 9,
    isNew: true,
    options: const ['S', 'M', 'L'],
  ),
];
