// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC70kDwi3Nfa-r0qgKRrGl62dkrMpTVYb8',
    appId: '1:659699596437:web:4d1b40a3da083be9472f9c',
    messagingSenderId: '659699596437',
    projectId: 'ceramic-app-aadcb',
    authDomain: 'ceramic-app-aadcb.firebaseapp.com',
    storageBucket: 'ceramic-app-aadcb.firebasestorage.app',
    measurementId: 'G-R0X4YQ16TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA089QiROh-Rodm09aKMjRitDDwoZ1pCb8',
    appId: '1:659699596437:android:76905183da9fcbec472f9c',
    messagingSenderId: '659699596437',
    projectId: 'ceramic-app-aadcb',
    storageBucket: 'ceramic-app-aadcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD01xUbCEA7wwQQE0n2iMAy5bR-JWKqsxU',
    appId: '1:659699596437:ios:d4999e730f14e425472f9c',
    messagingSenderId: '659699596437',
    projectId: 'ceramic-app-aadcb',
    storageBucket: 'ceramic-app-aadcb.firebasestorage.app',
    iosBundleId: 'com.example.ceramicApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD01xUbCEA7wwQQE0n2iMAy5bR-JWKqsxU',
    appId: '1:659699596437:ios:d4999e730f14e425472f9c',
    messagingSenderId: '659699596437',
    projectId: 'ceramic-app-aadcb',
    storageBucket: 'ceramic-app-aadcb.firebasestorage.app',
    iosBundleId: 'com.example.ceramicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC70kDwi3Nfa-r0qgKRrGl62dkrMpTVYb8',
    appId: '1:659699596437:web:f94ffe2cab119ec5472f9c',
    messagingSenderId: '659699596437',
    projectId: 'ceramic-app-aadcb',
    authDomain: 'ceramic-app-aadcb.firebaseapp.com',
    storageBucket: 'ceramic-app-aadcb.firebasestorage.app',
    measurementId: 'G-HW3B0XGEHW',
  );
}
